from validation.validator import Validator

segmentations_to_validate = [
    "data/Results/Segmentation_Results/Atlas/Atlas_Experiment01",
    "data/Results/Segmentation_Results/Atlas/Atlas_Experiment02",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment03",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment04",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment05",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment06",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment07",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment08",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment09",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment10",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment11",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment12",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment13",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment14",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment15",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment16",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment17",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment18",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment19",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment20",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment21",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment22",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment23",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment24",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment25",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment26",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment27",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment28",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment29",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment30",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment31",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment32",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment33",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment34",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment35",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment36",
    #
    # "data/Segmentation_Results/Atlas/Atlas_Experiment42",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment43",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment44",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment45",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment46",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment47",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment48",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment49",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment50",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment51",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment52",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment53",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment54",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment55",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment56",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment57",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment58",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment59",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment60",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment61",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment62",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment63",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment64",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment65",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment66",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment67",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment68",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment69",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment70",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment71",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment72",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment73",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment74",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment75",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment76",
    # "data/Segmentation_Results/Atlas/Atlas_Experiment77",
]
OUTPUT_DIR = "data/Results/Validation/"

if __name__ == "__main__":
    validator = Validator(ground_truth_dir="data/Images/Validation_Data_Small", output_dir=OUTPUT_DIR)

    for segmentations_dir in segmentations_to_validate:
        validator.validate(predictions_dir=segmentations_dir)
