from segmenter.atlas.refiner.color_patch_refiner import ColorPatchRefiner
from preprocessing.blue_color_preprocessor import BlueColorPreprocessor
from preprocessing.square_image_preprocessor import SquareImagePreprocessor
from preprocessing.torso_roi_preprocessor import TorsoRoiPreprocessor
from segmenter.ml_segmenter import MLSegmenter

SSL_BASE_OUTPUT_DIR = "data/Results/Segmentation_Results/SSL/"

ssl_segmenter = {
    # 1: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment01/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment01"
    # ),
    # 2: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment02/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment02"
    # ),
    # 3: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment03/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment03"
    # ),
    # 4: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment04/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment04"
    # ),
    # 5: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment05/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment05"
    # ),
    # 6: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment06/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment06"
    # ),
    # 7: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment07/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment07"
    # ),
    # 8: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment08/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment08"
    # ),
    # 9: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment09/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=9,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment09"
    # ),
    # 10: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment10/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=9,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment10"
    # ),
    # 11: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment11/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=25,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment11"
    # ),
    # 12: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment12/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=25,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment12"
    # ),
    #
    # 13: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment13/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment13"
    # ),
    # 14: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment14/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment14"
    # ),
    # 15: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment15/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment15"
    # ),
    # 16: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment16/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment16"
    # ),
    # 17: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment17/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment17"
    # ),
    # 18: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment18/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment18"
    # ),
    # 19: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment19/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment19"
    # ),
    # 20: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment20/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment20"
    # ),
    # 21: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment21/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=9,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment21"
    # ),
    # 22: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment22/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=9,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment22"
    # ),
    # 23: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment23/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=25,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment23"
    # ),
    # 24: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment24/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=25,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment24"
    # ),
    #
    # 25: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment25/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment25"
    # ),
    # 26: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment26/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment26"
    # ),
    # 27: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment27/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment27"
    # ),
    # 28: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment28/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment28"
    # ),
    # 29: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment29/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment29"
    # ),
    # 30: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment30/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment30"
    # ),
    # 31: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment31/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment31"
    # ),
    # 32: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment32/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment32"
    # ),
    # 33: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment33/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=9,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment33"
    # ),
    # 34: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment34/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=9,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment34"
    # ),
    # 35: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment35/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=25,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment35"
    # ),
    # 36: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment36/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=25,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment36"
    # ),
    #
    # 37: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment37/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment37"
    # ),
    # 38: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment38/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment38"
    # ),
    # 39: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment39/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment39"
    # ),
    # 40: MLSegmenter(
    #     model_type="segmentation_head",
    #     weights_path="data/SSL_Downstream/Experiment40/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment40"
    # ),
    # 41: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment41/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment41"
    # ),
    # 42: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment42/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment42"
    # ),
    # 43: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment43/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment43"
    # ),
    # 44: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment44/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=1000,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment44"
    # ),
    # 45: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment45/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=9,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment45"
    # ),
    # 46: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment46/best_model.pth",
    #     backbone="jigsaw_abs_pos",
    #     pretext_classes=9,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment46"
    # ),
    47: MLSegmenter(
        model_type="attention_unet",
        weights_path="data/SSL_Downstream/Experiment47/best_model.pth",
        backbone="jigsaw_abs_pos",
        pretext_classes=25,
        downstream_classes=1,
        device=None,
        preprocessing_steps=[SquareImagePreprocessor()],
        segmentation_refiner=None,
        output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment47"
    ),
    48: MLSegmenter(
        model_type="attention_unet",
        weights_path="data/SSL_Downstream/Experiment48/best_model.pth",
        backbone="jigsaw_abs_pos",
        pretext_classes=25,
        downstream_classes=1,
        device=None,
        preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
        segmentation_refiner=None,
        output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment48"
    ),

# 49: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment01/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment49"
#     ),
#     50: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment02/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment50"
#     ),
#     51: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment03/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment51"
#     ),
#     52: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment04/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment52"
#     ),
#     53: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment05/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment53"
#     ),
#     54: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment06/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment54"
#     ),
#     55: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment07/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment55"
#     ),
#     56: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment08/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment56"
#     ),
#     57: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment09/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=9,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment57"
#     ),
#     58: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment10/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=9,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment58"
#     ),
#     59: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment11/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=25,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment59"
#     ),
#     60: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment12/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=25,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment60"
#     ),
#
#     61: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment13/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment61"
#     ),
#     62: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment14/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment62"
#     ),
#     63: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment15/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment63"
#     ),
#     64: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment16/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment64"
#     ),
#     65: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment17/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment65"
#     ),
#     66: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment18/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment66"
#     ),
#     67: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment19/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment67"
#     ),
#     68: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment20/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment68"
#     ),
#     69: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment21/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=9,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment69"
#     ),
#     70: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment22/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=9,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment70"
#     ),
#     71: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment23/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=25,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment71"
#     ),
#     72: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment24/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=25,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment72"
#     ),
#
#     73: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment25/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment73"
#     ),
#     74: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment26/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment74"
#     ),
#     75: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment27/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment75"
#     ),
#     76: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment28/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment76"
#     ),
#     77: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment29/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment77"
#     ),
#     78: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment30/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment78"
#     ),
#     79: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment31/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment79"
#     ),
#     80: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment32/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment80"
#     ),
#     81: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment33/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=9,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment81"
#     ),
#     82: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment34/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=9,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment82"
#     ),
#     83: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment35/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=25,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment83"
#     ),
#     84: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment36/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=25,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment84"
#     ),
#
#     85: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment37/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment85"
#     ),
#     86: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment38/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment86"
#     ),
#     87: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment39/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment87"
#     ),
#     88: MLSegmenter(
#         model_type="segmentation_head",
#         weights_path="data/SSL_Downstream/Experiment40/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment88"
#     ),
#     89: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment41/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment89"
#     ),
#     90: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment42/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=100,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment90"
#     ),
#     91: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment43/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment91"
#     ),
#     92: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment44/best_model.pth",
#         backbone="jigsaw_perm",
#         pretext_classes=1000,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment92"
#     ),
#     93: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment45/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=9,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment93"
#     ),
#     94: MLSegmenter(
#         model_type="attention_unet",
#         weights_path="data/SSL_Downstream/Experiment46/best_model.pth",
#         backbone="jigsaw_abs_pos",
#         pretext_classes=9,
#         downstream_classes=1,
#         device=None,
#         preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
#         segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
#         output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment94"
#     ),
    95: MLSegmenter(
        model_type="attention_unet",
        weights_path="data/SSL_Downstream/Experiment47/best_model.pth",
        backbone="jigsaw_abs_pos",
        pretext_classes=25,
        downstream_classes=1,
        device=None,
        preprocessing_steps=[SquareImagePreprocessor()],
        segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
        output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment95"
    ),
    96: MLSegmenter(
        model_type="attention_unet",
        weights_path="data/SSL_Downstream/Experiment48/best_model.pth",
        backbone="jigsaw_abs_pos",
        pretext_classes=25,
        downstream_classes=1,
        device=None,
        preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
        segmentation_refiner=ColorPatchRefiner(color_preprocessor=BlueColorPreprocessor()),
        output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment96"
    ),
    #
    # 97: MLSegmenter(
    #     model_type="attention_unet",
    #     weights_path="data/SSL_Downstream/Experiment97/best_model.pth",
    #     backbone="jigsaw_perm",
    #     pretext_classes=100,
    #     downstream_classes=1,
    #     device=None,
    #     preprocessing_steps=[TorsoRoiPreprocessor(target_ratio=5 / 7), SquareImagePreprocessor()],
    #     segmentation_refiner=None,
    #     output_dir=SSL_BASE_OUTPUT_DIR + "SSL_Experiment97"
    # ),
}